"""Add Conversation and Message models

Revision ID: 3164f08f586f
Revises: cd40814447b7
Create Date: 2025-10-23 14:33:14.121252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3164f08f586f'
down_revision: Union[str, None] = 'cd40814447b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('title', sa.String(length=512), nullable=True))
    op.add_column('conversations', sa.Column('messages_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('messages', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('messages', sa.Column('message_metadata', sa.JSON(), nullable=True))
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('messages', 'message_metadata')
    op.drop_column('messages', 'status')
    op.drop_column('conversations', 'messages_count')
    op.drop_column('conversations', 'title')
    # ### end Alembic commands ###
